### ISSUE TITLE
Does not work with runabove object storage

### ISSUE THREAD

**Issue by riccardobl** [cloudfs/ftp-cloudfs#49]
With runabove.com object storage i get this error when i try to upload something

```
[16337] 2015-08-04 17:02:17,271 - INFO - Starting new HTTPS connection (1): storage.sbg-1.runabove.io
[16457] 2015-08-04 17:02:17,274 - DEBUG - ObjectStorageFD object: u'xxxx' (mode: 'wb')
[16457] 2015-08-04 17:02:17,274 - DEBUG - write fd u'xxxx'
[16457] 2015-08-04 17:02:17,274 - DEBUG - ChunkedObject: path=u'/v1/AUTH_xxxx/xxxx/xxxx', headers={'Transfer-Encoding': 'chunked', 'Connection': 'close', 'Content-Type': 'application/octet-stream', 'X-Forwarded-For': '127.0.0.1', 'X-Auth-Token': u'xxxx'}
[16457] 2015-08-04 17:02:17,274 - DEBUG - called fs.close()
[I 15-08-04 17:02:17] 127.0.0.1:47987-[xxxx] STOR /xxxx 150
[16457] 2015-08-04 17:02:17,274 - INFO - 127.0.0.1:47987-[xxxx] STOR xxxx 150
[16457] 2015-08-04 17:02:17,275 - DEBUG - ChunkObject: new connection open (ParseResult(scheme=u'https', netloc=u'storage.sbg-1.runabove.io', path=u'/v1/AUTH_xxxx', params='', query='', fragment=''), <swiftclient.client.HTTPConnection instance at 0x7f34d39dedd0>)
[E 15-08-04 17:02:17] unhandled exception in instance <ftpcloudfs.monkeypatching.MyDTPHandler (addr=127.0.0.1:58053, user=u'xxxx', receive=True, file=u'xxxx') at 0x7f34d39defc8>
    Traceback (most recent call last):
      File "/usr/lib/python2.7/asyncore.py", line 83, in read
        obj.handle_read_event()
      File "/usr/local/lib/python2.7/dist-packages/pyftpdlib/handlers.py", line 785, in handle_read
        self.file_obj.write(chunk)
      File "/usr/local/lib/python2.7/dist-packages/ftpcloudfs/fs.py", line 108, in wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/ftpcloudfs/fs.py", line 267, in write
        self.obj.send_chunk(data)
      File "/usr/local/lib/python2.7/dist-packages/ftpcloudfs/chunkobject.py", line 55, in send_chunk
        self._open_connection()
      File "/usr/local/lib/python2.7/dist-packages/ftpcloudfs/chunkobject.py", line 46, in _open_connection
        self.raw_conn = self.conn.request_session.get_adapter(self.url).get_connection(self.url)._get_conn()
    AttributeError: HTTPConnection instance has no attribute 'request_session'

```

**Comment by reidrac** [comment]
I need to know which versions are you using. Can you provide the output of `pip freeze` or similar?

Sounds to me that the problem could be the requests version.

**Comment by reidrac** [comment]
This looks like the same problem in #36.

You should be using python-swiftclient 2.1.0, otherwise it wont' work.

**Comment by reidrac** [comment]
Feel free to reopen the issue if upgrading swiftclient version doesn't fix the issue for you!
