### ISSUE TITLE
Issues decoding unicode string in X-Object-Manifest

### ISSUE THREAD

**Issue by reidrac** [cloudfs/ftp-cloudfs#52]
Sometimes we got error on DLO objects like:
```
File "/usr/local/lib/python2.7/dist-packages/ftpcloudfs/fs.py", line 496, in listdir_container
  manifests[obj['name']] = unicode(unquote(manifest_obj['x-object-manifest']), "utf-8")
TypeError: decoding Unicode is not supported
```
If manifest_obj['x-object-manifest'] is a unicode instance, than exception throws. 

Example:
```
curl -X PUT \
  -H "X-Auth-Token: ${TOKEN}" \
  --data-binary "" \
  "${MAIN_URL}/${CONTAINER}"

curl -X PUT \
  -H "X-Auth-Token: ${TOKEN}" \
  --data-binary "01" \
  "${MAIN_URL}/${CONTAINER}/test_obj/01"

curl -X PUT \
  -H "X-Auth-Token: ${TOKEN}" \
  -H "X-Object-Manifest: ${CONTAINER}/test_obj/" \
  --data-binary "" \
  "${MAIN_URL}/${CONTAINER}/test_obj"
```

And then listing abort connection on client-side:
```
~ $: ftp ftp://${OS_TENANT_NAME}.${OS_USERNAME}:${OS_PASSWORD}@${OS_FTP_URL}
Connected to $OS_FTP_URL.
220 ftp-cloudfs 0.34 using pyftpdlib 1.5.0 ready.
331 Username ok, send password.
230 Welcome $OS_TENANT_NAME.$OS_USERNAME
Remote system type is UNIX.
Using binary mode to transfer files.
200 Type set to: Binary.
ftp> cd $CONTAINER
250 "/$CONTAINER" is the current directory.
ftp> ls
229 Entering extended passive mode (|||52088|).
421 Service not available, remote server has closed connection.
```
.. and server-side:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/root/ftpcloudfs/local/lib/python2.7/site-packages/pyftpdlib/ioloop.py", line 919, in handle_read
    asynchat.async_chat.handle_read(self)
  File "/usr/lib/python2.7/asynchat.py", line 158, in handle_read
    self.found_terminator()
  File "/root/ftpcloudfs/local/lib/python2.7/site-packages/pyftpdlib/handlers.py", line 1379, in found_terminator
    self.pre_process_command(line, cmd, arg)
  File "/root/ftpcloudfs/local/lib/python2.7/site-packages/pyftpdlib/handlers.py", line 1485, in pre_process_command
    self.process_command(cmd, arg, **kwargs)
  File "/root/ftpcloudfs/local/lib/python2.7/site-packages/ftpcloudfs/monkeypatching.py", line 51, in process_command
    FTPHandler.process_command(self, cmd, *args, **kwargs)
  File "/root/ftpcloudfs/local/lib/python2.7/site-packages/pyftpdlib/handlers.py", line 1496, in process_command
    method(*args, **kwargs)
  File "/root/ftpcloudfs/local/lib/python2.7/site-packages/pyftpdlib/handlers.py", line 2082, in ftp_LIST
    iterator = self.run_as_current_user(self.fs.get_list_dir, path)
  File "/root/ftpcloudfs/local/lib/python2.7/site-packages/pyftpdlib/handlers.py", line 1755, in run_as_current_user
    return function(*args, **kwargs)
  File "/root/ftpcloudfs/local/lib/python2.7/site-packages/pyftpdlib/filesystems.py", line 373, in get_list_dir
    listing = self.listdir(path)
  File "/root/ftpcloudfs/local/lib/python2.7/site-packages/ftpcloudfs/fs.py", line 132, in wrapper
    return fn(obj, *args, **kwargs)
  File "/root/ftpcloudfs/local/lib/python2.7/site-packages/ftpcloudfs/fs.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/root/ftpcloudfs/local/lib/python2.7/site-packages/ftpcloudfs/fs.py", line 799, in listdir
    list_dir = map(lambda x: unicode(x, 'utf-8'), self._listdir_cache.listdir(path))
  File "/root/ftpcloudfs/local/lib/python2.7/site-packages/ftpcloudfs/fs.py", line 551, in listdir
    self.listdir_container(cache, container, obj)
  File "/root/ftpcloudfs/local/lib/python2.7/site-packages/ftpcloudfs/fs.py", line 496, in listdir_container
    manifests[obj['name']] = unicode(unquote(manifest_obj['x-object-manifest']), "utf-8")
TypeError: decoding Unicode is not supported
```

This comes from  #51.

**Comment by reidrac** [comment]
cc: @vills

**Comment by reidrac** [comment]
I run all the tests with pyftpdlib 1.5.0 and everything works as expected.

@vills: can you provide the container name you're using for the test?

**Comment by vills** [comment]
Hi there,
Sure. Container name is "test" :-)

**Comment by reidrac** [comment]
OK, thanks.

**Comment by vills** [comment]
On which version of Swift you test?

**Comment by reidrac** [comment]
OK, I managed to reproduce the issue with python-swiftclient==3.0.0 and pyftpdlib 1.5.0.

As workaround, you can use python-swiftclient==2.x and it seems to be fine, looks like the problem was introduced by python-swiftclient==3.0.0 release.

**Comment by vills** [comment]
In my test environment python-swiftclient version 2.7 installed:
```
(ftpcloudfs)root@ftpcloudfs:~# pip freeze | egrep 'pyftpdlib|swift'
pyftpdlib==1.5.0
python-swiftclient==2.7.0
```

And all environment:
```
(ftpcloudfs)root@ftpcloudfs:~# pip freeze
Babel==2.2.0
argparse==1.2.1
debtcollector==1.3.0
docutils==0.12
ftp-cloudfs==0.34
funcsigs==0.4
futures==3.0.5
iso8601==0.1.11
keystoneauth1==2.3.0
lockfile==0.12.2
monotonic==0.6
msgpack-python==0.4.7
netaddr==0.7.18
netifaces==0.10.4
oslo.config==3.9.0
oslo.i18n==3.4.0
oslo.serialization==2.4.0
oslo.utils==3.7.0
pbr==1.8.1
positional==1.0.1
prettytable==0.7.2
pyftpdlib==1.5.0
python-daemon==2.1.1
python-keystoneclient==2.3.1
python-memcached==1.57
python-swiftclient==2.7.0
pytz==2015.7
requests==2.9.1
six==1.10.0
stevedore==1.12.0
wrapt==1.10.6
wsgiref==0.1.2
```

**Comment by reidrac** [comment]
OK, thanks again. I was using an old swiftclient version apparently. I upgraded to 3.0.0 to run the tests and managed to reproduce the issue.

**Comment by vills** [comment]
I test on python-swiftclient 2.6.0 version - works ok. Bug appears starting from 2.7.0.

From 2.7.0 changelog:
> Fixed bug when deleting DLOs with unicode characters

Sure, it is connected ;)

**Comment by reidrac** [comment]
It should be fixed in a941acb31ab0065123e7e237299336295139c486 can you give it a go?

It should be compatible now with swifclient < 2.7.0 and later version.

**Comment by vills** [comment]
Yep, it works fine!

**Comment by reidrac** [comment]
Excellent! Thanks.
