### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by isetsuna** [cloudfs/ftp-cloudfs#53]
HI,

I was use ftp-cloudfs in ConoHa Object Storage Service.
Start the ftp-cloudfs like so:
` ftpcloudfs --foreground --keystone-auth --auth-url=https://identity.tyo1.cloud.z.com/v2.0`
FTP USERNAME : zjpt????.zjpu????
FTP PASSWORD : ConoHa API PASSWORD

It can be connect and download or create/delete containers.
But when I upload,it prompts error:
```
150 File status okay. About to open data connection.
421 Data connection error (name must be a byte string)
```

```
[32628] 2016-03-23 00:35:17,106 - INFO - xx.xx.xx.xx:9429-[zjpt????.zjpu????] Data connection error (name must be a byte string)
[32628] 2016-03-23 00:35:17,106 - WARNING - xx.xx.xx.xx:9429-[zjpt????.zjpu????] Internal error; transfer aborted.
[32628] 2016-03-23 00:35:17,501 - INFO - Starting new HTTPS connection (1): object-storage.tyo1.cloud.z.com
[32628] 2016-03-23 00:35:17,612 - INFO - Starting new HTTPS connection (1): object-storage.tyo1.cloud.z.com
[32628] 2016-03-23 00:35:18,085 - INFO - xx.xx.xx.xx:9429-[zjpt????.zjpu????] STOR /1/DSC_0482.jpg 150
[32628] 2016-03-23 00:35:18,292 - INFO - Starting new HTTPS connection (1): object-storage.tyo1.cloud.z.com
[32628] 2016-03-23 00:35:18,306 - ERROR - unhandled exception in instance <ftpcloudfs.monkeypatching.MyDTPHandler (addr=xx.xx.xx.xx:9432, user=u'zjpt????.zjpu????', receive=True, file=u'DSC_0482.jpg')>
Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/local/lib/python2.7/dist-packages/pyftpdlib-1.5.0-py2.7.egg/pyftpdlib/handlers.py", line 792, in handle_read
    self.file_obj.write(chunk)
  File "/usr/local/lib/python2.7/dist-packages/ftp_cloudfs-0.35-py2.7.egg/ftpcloudfs/fs.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ftp_cloudfs-0.35-py2.7.egg/ftpcloudfs/fs.py", line 267, in write
    self.obj.send_chunk(data)
  File "/usr/local/lib/python2.7/dist-packages/ftp_cloudfs-0.35-py2.7.egg/ftpcloudfs/chunkobject.py", line 55, in send_chunk
    self._open_connection()
  File "/usr/local/lib/python2.7/dist-packages/ftp_cloudfs-0.35-py2.7.egg/ftpcloudfs/chunkobject.py", line 51, in _open_connection
    self.raw_conn.endheaders()
  File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/lib/python2.7/dist-packages/urllib3/connection.py", line 237, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 277, in ssl_wrap_socket
    cnx.set_tlsext_host_name(server_hostname)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 916, in set_tlsext_host_name
    raise TypeError("name must be a byte string")
TypeError: name must be a byte string
```

How should I do?Thanks.

**Comment by reidrac** [comment]
It could be a bug related to the way we delay opening the connection when we upload the file.

Can you tell me which version of python-swiftclient, python-keystoneclient and requests are you using?

**Comment by isetsuna** [comment]
I was install it from Debian Jessie. = =||

**Comment by reidrac** [comment]
Jessie ships 0.25.2; that's quite old I'm afraid.

Can you check this guide?

https://github.com/cloudfs/ftp-cloudfs/wiki/QuickStart

I recommend you setting a virtual environment and running the latest version to see if we can reproduce the issue.

**Comment by isetsuna** [comment]
Hi,I'm here again.

Python 2.7.11 & pip 8.1.1

It can work properly.

Thanks very much!

**Comment by reidrac** [comment]
You're welcome!
