### ISSUE TITLE
No help with wrong /etc/ftpcloudfs.conf 

### ISSUE THREAD

**Issue by vills** [cloudfs/ftp-cloudfs#55]
If we have `/etc/ftpcloudfs.conf` file (default location) and it has no section headers, that we can't see `ftpcloudfs` binary help information. Printing help information should be earlier in code, than parsing conf-file.

How to reproduce:
```
~# ftpcloudfs -h
Usage: ftpcloudfs [options]

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
[ ... ]


~# echo 'port=21' > /etc/ftpcloudfs.conf


~# ftpcloudfs -h
Traceback (most recent call last):
  File "/usr/local/bin/ftpcloudfs", line 18, in <module>
    main.main()
  File "/usr/local/lib/python2.7/dist-packages/ftpcloudfs/main.py", line 366, in main
    self.parse_configuration()
  File "/usr/local/lib/python2.7/dist-packages/ftpcloudfs/main.py", line 131, in parse_configuration
    if not config.read(config_file) and alt_config_file:
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
ConfigParser.MissingSectionHeaderError: File contains no section headers.
file: /etc/ftpcloudfs.conf, line: 1
'port=21\n'
```

**Comment by reidrac** [comment]
Thanks for the report.
