### ISSUE TITLE
Swift client issue

### ISSUE THREAD

**Issue by renoovodesign** [cloudfs/ftp-cloudfs#57]
Hi,

I'm running CentOS 6.7
I've installed pip using yum
I have updated ftp-cloudfs from 0.32 to 0.35 as well as all my pip packages using this command:

`# pip install ftp-cloudfs --upgrade`

This is the proof that all the requirements are met:
```
Requirement already satisfied (use --upgrade to upgrade): ftp-cloudfs in /usr/lib/python2.6/site-packages
Requirement already satisfied (use --upgrade to upgrade): pyftpdlib>=1.3.0 in /usr/lib/python2.6/site-packages (from ftp-cloudfs)
Requirement already satisfied (use --upgrade to upgrade): python-swiftclient>=2.1.0 in /usr/lib/python2.6/site-packages (from ftp-cloudfs)
Requirement already satisfied (use --upgrade to upgrade): python-daemon>=1.5.5 in /usr/lib/python2.6/site-packages (from ftp-cloudfs)
Requirement already satisfied (use --upgrade to upgrade): python-memcached in /usr/lib/python2.6/site-packages (from ftp-cloudfs)
Requirement already satisfied (use --upgrade to upgrade): futures>=2.1.3 in /usr/lib/python2.6/site-packages (from python-swiftclient>=2.1.0->ftp-cloudfs)
Requirement already satisfied (use --upgrade to upgrade): requests>=1.1 in /usr/lib/python2.6/site-packages (from python-swiftclient>=2.1.0->ftp-cloudfs)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in /usr/lib/python2.6/site-packages (from python-swiftclient>=2.1.0->ftp-cloudfs)
Requirement already satisfied (use --upgrade to upgrade): docutils in /usr/lib/python2.6/site-packages (from python-daemon>=1.5.5->ftp-cloudfs)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python2.6/site-packages (from python-daemon>=1.5.5->ftp-cloudfs)
Requirement already satisfied (use --upgrade to upgrade): lockfile>=0.10 in /usr/lib/python2.6/site-packages (from python-daemon>=1.5.5->ftp-cloudfs)
```

I am now getting an error when running ftpcloudfs command:
```
Traceback (most recent call last):
  File "/usr/bin/ftpcloudfs", line 14, in <module>
    from ftpcloudfs.main import Main
  File "/usr/lib/python2.6/site-packages/ftpcloudfs/main.py", line 14, in <module>
    import swiftclient
  File "/usr/lib/python2.6/site-packages/swiftclient/__init__.py", line 20, in <module>
    from .client import *  # noqa
  File "/usr/lib/python2.6/site-packages/swiftclient/client.py", line 136
    return {key: safe_value(key, val) for (key, val) in headers}
                                        ^
SyntaxError: invalid syntax
```

Please could you provide any pointers?

**Comment by reidrac** [comment]
That's a swiftclient problem; that dict comprehension style won't work in python < 2.7.

Which version of swiftclient are you using? swiftclient >= 3 requires python 2.7.

2.6.0 was the latest swiftclient supporting python 2.6. You can try to force python-swiftclient install with pip to a specific version; eg:
```
pip install python-swiftclient==2.6.0
```

**Comment by renoovodesign** [comment]
Thank you for getting back to me. I have found the same resolution just before you replied. With the help of this:
[](https://www.swiftstack.com/docs/integration/python-swiftclient.html)

I would have thought pip would have worked out which swiftclient version to provide me with depending on my version of python. But it didn't.
Instead it installed swiftclient 3, whilst I am using python 2.6.6. 


Issue fixed after doing:
`# pip install python-swiftclient==2.7.0`

**Comment by reidrac** [comment]
May we you could file a bug report for pip :)
