### ISSUE TITLE
Failed to retrieve directory listing

### ISSUE THREAD

**Issue by xxditixx** [cloudfs/ftp-cloudfs#61]
Hello,

When i try to connect via FTP, i can successfully login but the directory will not get listed. (using FileZilla as a ftp client)

ftpcloudfs logs:

2016-12-22 09:43:03,520 - INFO - >>> starting FTP server on 109.*.*.*:2021, pid=3347 <<<
2016-12-22 09:43:03,520 - INFO - poller: <class 'pyftpdlib.ioloop.Epoll'>
2016-12-22 09:43:03,521 - INFO - masquerade (NAT) address: None
2016-12-22 09:43:03,521 - INFO - passive ports: None
2016-12-22 09:43:03,521 - INFO - use sendfile(2): False
2016-12-22 09:43:03,521 - INFO - dispatcher: <class pyftpdlib.servers.MultiprocessFTPServer at 0x7f267685a390>
2016-12-22 09:43:09,033 - INFO - 91.*.*.*:56891-[] FTP session opened (connect)
2016-12-22 09:43:09,165 - INFO - 91.*.*.*:56891-[test cloud project.ani] Authentication validated for user test cloud project.ani
2016-12-22 09:43:09,165 - INFO - 91.*.*.*:56891-[test cloud project.ani] USER 'test cloud project.ani' logged in.
2016-12-22 09:43:09,189 - ERROR - unhandled exception in instance <ftpcloudfs.monkeypatching.MyFTPHandler (addr=91.*.*.*:56891, user=u' test clou$
Traceback (most recent call last):
  File "/usr/lib/python2.7/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "/usr/lib/python2.7/asynchat.py", line 158, in handle_read
    self.found_terminator()
  File "/usr/lib/python2.7/dist-packages/pyftpdlib/handlers.py", line 1322, in found_terminator
    self.pre_process_command(line, cmd, arg)
  File "/usr/lib/python2.7/dist-packages/pyftpdlib/handlers.py", line 1428, in pre_process_command
    self.process_command(cmd, arg, **kwargs)
  File "/usr/lib/python2.7/dist-packages/ftpcloudfs/monkeypatching.py", line 51, in process_command
    FTPHandler.process_command(self, cmd, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyftpdlib/handlers.py", line 1439, in process_command
    method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyftpdlib/handlers.py", line 2113, in ftp_MLSD
    if not self.fs.isdir(path):
  File "/usr/lib/python2.7/dist-packages/ftpcloudfs/fs.py", line 901, in isdir
    return stat.S_ISDIR(self.stat(path).st_mode)
  File "/usr/lib/python2.7/dist-packages/ftpcloudfs/fs.py", line 102, in wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/ftpcloudfs/fs.py", line 949, in stat
    return self._listdir_cache.stat(path)
  File "/usr/lib/python2.7/dist-packages/ftpcloudfs/fs.py", line 552, in stat
    self.listdir(directory)
  File "/usr/lib/python2.7/dist-packages/ftpcloudfs/fs.py", line 499, in listdir
    self.listdir_root(cache)
  File "/usr/lib/python2.7/dist-packages/ftpcloudfs/fs.py", line 472, in listdir_root
    _, objects = self.conn.get_account()
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1724, in get_account
    full_listing=full_listing, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 1673, in _retry
    service_token=self.service_token, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/swiftclient/client.py", line 758, in get_account
    conn.request(method, full_path, '', req_headers)
  File "/usr/lib/python2.7/dist-packages/ftpcloudfs/fs.py", line 66, in request_x_forwarded_for
    fn(method, url, body=body, headers=headers)
TypeError: request() got an unexpected keyword argument 'body'
2016-12-22 09:43:09,191 - INFO -91.*.*.*:56891-[test cloud project.ani] FTP session closed (disconnect).

**Comment by reidrac** [comment]
Can you tell us the version of python-swiftclient and requests you have installed?

Looks like the requests version is incompatible. We don't enforce a specific version of requests, may be we should.

**Comment by xxditixx** [comment]
Hello reidrac and thank you for the reply.

Requirement already satisfied: python-swiftclient in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: requests>=1.1 in /usr/local/lib/python2.7/dist-packages (from python-swiftclient)
Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python2.7/dist-packages (from python-swiftclient)
Requirement already satisfied: futures>=3.0; python_version == "2.7" or python_version == "2.6" in /usr/local/lib/python2.7/dist-packages (from python-swiftclient)

**Comment by reidrac** [comment]
Those aren't the versions.

If you're using pip, please run `pip freeze` and get the versions from there.

**Comment by xxditixx** [comment]
Here it is:

apt-xapian-index==0.45
Babel==1.3
chardet==2.0.1
Cheetah==2.4.4
cloud-init==0.7.5
configobj==4.7.2
docutils==0.11
eventlet==0.13.0
ftp-cloudfs==0.25.2
futures==3.0.5
greenlet==0.4.2
httplib2==0.8
iso8601==0.1.10
jsonpatch==1.3
jsonpointer==1.0
Landscape-Client==14.12
lockfile==0.8
netaddr==0.7.10
oauth==1.0.1
oslo.config==1.2.1
PAM==0.4.2
pbr==0.7.0
Pillow==2.3.0
prettytable==0.7.2
pycurl==7.19.3
pyftpdlib==1.2.0
Pygments==1.6
pyOpenSSL==0.13
pyserial==2.6
python-apt===0.9.3.5ubuntu1
python-cloudfiles==1.7.10
python-daemon==1.5.5
python-debian===0.1.21-nmu2ubuntu2
python-keystoneclient==0.7.1
python-memcached==1.53
python-swiftclient==3.2.0
pytz==2012rc0
PyYAML==3.10
requests==2.12.4
roman==2.0.0
simplejson==3.3.1
six==1.10.0
ssh-import-id==3.21
Twisted-Core==13.2.0
Twisted-Names==13.2.0
Twisted-Web==13.2.0
urllib3==1.7.1
zope.interface==4.0.5

**Comment by reidrac** [comment]
Oh, sorry. I missed the fact that you're running a very old version of ftpclooudfs!

ftp-cloudfs==0.25.2 is outdated; python-swiftclient 2.x uses Requests and it is currently incompatible with ftp-cloudfs < 0.30.

Please update ftp-cloudfs to the latest version and your problem will be solved.

You can do it with pip; `pip install --upgrade ftp-cloudfs`. If you installed ftp-cloudfs from your distro packages I recommend you to uninstall it first.

**Comment by xxditixx** [comment]
I tested again on a fresh image:
ftp-cloudfs==0.35
python-keystoneclient==2.3.1
python-memcached==1.58
python-swiftclient==3.2.0
requests==2.12.4

On filezilla i cannot still list the directories even though now im not getting errors on ftpcloudfs log file.

**Comment by reidrac** [comment]
Can you share the error log?

Although looks like you could be using a restricted user. Only the account admin can list the root directory; if you assign any other user a container's ACL, the user will be able to use that container but NOT to list the root directory.

**Comment by xxditixx** [comment]
After following the steps carefully i could decide that security rules were blocking the directory listing.
I allowed every single port from my openstack dashboard and now it works.

**Comment by reidrac** [comment]
Excellent! :+1:
