### ISSUE TITLE
Is it required to manually run ftpcloudfs before running test_ftpcloudfs unittests?

### ISSUE THREAD

**Issue by treyd** [cloudfs/ftp-cloudfs#62]
I am trying to set up a dev environment for ftp-cloudfs and I'm having trouble running the unittests in the tests directory.  When I run the tests all of the tests in test_ftpcloudfs.py fail with the following error:

```
Error
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 320, in run
    self.setUp()
  File "/Users/trey/git/ftp-cloudfs/tests/test_ftpcloudfs.py", line 36, in setUp
    self.cnx.connect()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ftplib.py", line 135, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 61] Connection refused
```

Tracing through the test code, the setUp function for the test case tries to set up an FTP connection to presumably test the FTP interface of ftpcloudfs, but I don't see anything in there that launches the FTP server.  Am I supposed to manually launch it before running the tests in this module?

**Comment by reidrac** [comment]
You must start the FTP server manually, at least for the code that tests the coded that interfaces with pyftppdlib.
