### ISSUE TITLE
Account GET errors are too noisy

### ISSUE THREAD

**Issue by reidrac** [cloudfs/ftp-cloudfs#8]
When a non-admin user tries to list the root directory it doesn't have enough permissions to do that. We keep going to allow those users to cd to a container with the proper ACL.

We shouldn't log these "Account GET" errors as they don't mean anything and just make useless noise in the logs.

I've started to notice this after upgrading python-swiftlient to 1.7.0, so it could be related.

Example:

```
Oct 18 10:57:58 *hostname* ftpcloudfs[1656]: Account GET failed: https://proxy:443/v1/AUTH_*ACCOUNT*?format=json 403 Forbidden   403 Forbidden#012#012Access was denied to this resource.#012#012   #012Traceback (most recent call last):#012  File "/usr/lib/pymodules/python2.6/swiftclient/client.py", line 1110, in _retry#012    rv = func(self.url, self.token, *args, **kwargs)#012  File "/usr/lib/pymodules/python2.6/swiftclient/client.py", line 392, in get_account#012    http_response_content=body)#012ClientException: Account GET failed: https://proxy:443/v1/AUTH_*ACCOUNT*?format=json 403 Forbidden   403 Forbidden#012#012Access was denied to this resource.#012#012 
```

**Comment by reidrac** [comment]
Won't fix.
